name: Deploy Node.js Microservice to AWS ECS via Docker Hub

on:
  push:
    branches:
      - main # Runs when changes are pushed to the main branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build & Push Docker Image to Docker Hub
      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          IMAGE_TAG=$(date +%s)
          docker build -t $DOCKERHUB_USERNAME/node-service:$IMAGE_TAG .
          docker tag $DOCKERHUB_USERNAME/node-service:$IMAGE_TAG $DOCKERHUB_USERNAME/node-service:latest
          docker push $DOCKERHUB_USERNAME/node-service:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/node-service:latest
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # Step 5: Configure AWS CLI
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-north-1  # Change region if needed

      # Step 6: Verify AWS Credentials
      - name: Verify AWS CLI Credentials
        run: aws sts get-caller-identity

      # Step 7: Update ECS Task Definition with Latest Image
      - name: Update ECS Task Definition with Latest Image
        run: |
          TASK_DEFINITION_NAME="programingNode"

          # Get the latest task definition JSON
          TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition $TASK_DEFINITION_NAME --query 'taskDefinition' --output json)

          # Modify the container image and remove unnecessary parameters
          UPDATED_TASK_DEF=$(echo "$TASK_DEF_JSON" | jq --arg IMAGE "${{ secrets.DOCKERHUB_USERNAME }}/node-service:$IMAGE_TAG" '
            .containerDefinitions[0].image = $IMAGE |
            del(.taskDefinitionArn, .status, .revision, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)
          ')

          # Save the updated task definition to a file
          echo "$UPDATED_TASK_DEF" > updated-task-def.json

          # Register the new task definition
          aws ecs register-task-definition --cli-input-json file://updated-task-def.json

      # Step 8: Force ECS Deployment with Updated Task Definition
      - name: Force ECS Deployment with Updated Task
        run: |
          aws ecs update-service \
            --cluster programingAutograderNode \
            --service programingNodeService \
            --force-new-deployment
